[package]
name = "rduco"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
crossterm = "0.26"
serde_json = "1.0"
sha1 = "0.10"
hex = "0.4"
